baseURL = 'https://example.com'
languageCode = 'en-us'
title = 'Vonge'
# 如需在主题目录内单独运行站点，请在你的站点配置中添加：theme = 'vonge-hugo'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

[pagination]
	pagerSize = 6

[taxonomies]
	tag = 'tags'

[params]
	logo_image = 'images/logo.svg'
	social_media_share_image = '/images/01.jpg'
	disqus_identifier = ''
	google_analytics = ''
	twitter_handle = ''
	author_image = '/images/avatar.jpg'

