name = "vonge-hugo"
license = "MIT"
licenselink = "LICENSE"
description = "Vonge is a portfolio and blog theme inspired by the Zola Vonge theme."
homepage = "https://github.com/vincent-sha/vonge-hugo"

[author]
  name = "vincent-sha"
  homepage = "https://vincent-blog.top/"

[original]
  name = "Vonge (Zola theme)"
  homepage = ""
  repo = ""

[min_version]
  hugo = "0.111.0"
