baseURL = 'https://vincent-strapi.top'
languageCode = 'en-us'
title = 'Vonge'
theme = 'vonge-hugo'

[pagination]
	pagerSize = 6

[taxonomies]
	tag = 'tags'

[params]
	author = 'Vanessa Marley'
	description = 'Vonge is a portfolio site template for Zola'
	logo_image = 'images/logo.svg'
	social_media_share_image = '/images/01.jpg'
	disqus_identifier = ''
	google_analytics = ''
	twitter_handle = ''
	author_image = '/images/avatar.jpg'
	date_format = '02 Jan 2006'
	language_direction = 'auto'
	keywords = ['keyword1', 'keyword2', 'keyword3']

	[[params.navigation]]
		url = '$BASE_URL'
		title = 'Home'
	[[params.navigation]]
		url = '$BASE_URL/projects'
		title = 'Projects'
	[[params.navigation]]
		url = '$BASE_URL/posts'
		title = 'Blog'
	[[params.navigation]]
		url = '$BASE_URL/tags'
		title = 'Tags'
	[[params.navigation]]
		url = ''
		title = 'Pages'
		[[params.navigation.submenu]]
			url = '$BASE_URL/about'
			title = 'About'
		[[params.navigation.submenu]]
			url = '$BASE_URL/elements'
			title = 'Elements'

	[[params.social_icons]]
		url = 'https://github.com/cydave'
		icon = 'GitHub'
	[[params.social_icons]]
		url = 'https://twitter.com/_cydave'
		icon = 'Twitter'
	[[params.social_icons]]
		url = '$BASE_URL/atom.xml'
		icon = 'RSS'
	[[params.social_icons]]
		url = 'https://pinterest.com'
		icon = 'Pinterest'

	[params.newsletter]
		newsletter_title = 'Join my mailing list'
		newsletter_identifier = ''
		newsletter_button = 'Subscribe'
		newsletter_description = 'Get inspiration, updates and, cool stuff!'

	[params.footer]
		[[params.footer.menu]]
			url = '$BASE_URL'
			title = 'Home'
		[[params.footer.menu]]
			url = '$BASE_URL/projects/'
			title = 'Projects'
		[[params.footer.menu]]
			url = '$BASE_URL/elements/'
			title = 'Elements'
		[[params.footer.menu]]
			url = '$BASE_URL/about/'
			title = 'About'
		[[params.footer.menu]]
			url = '$BASE_URL/posts/'
			title = 'Blog'

	[[params.content_blocks]]
		block = 'hero'
		title = 'Hi there, I am Vanessa Marley'
		description_html = '<strong>Photographer</strong> and Visual Content Strategist from Albany. I work as a lifestyle, product, and landscape photographer, creating images for a diverse range of requests, from online media to printed artwork.'
		image = '/images/01.jpg'
		image_alt = "Vanessa Marley's picture"
		cta_button_link = '#contact'
		cta_button = 'Get in touch'
		works_button_link = '#projects'
		works_button = 'See my works'

	[[params.content_blocks]]
		block = 'projects-section'
		title = 'Latest Works'
		description_html = '<p>I show only my best works built completely with passion, simplicity, and creativity!</p>'
		link_url = '/projects'
		show_projects = true

	[[params.content_blocks]]
		block = 'testimonials-section'
		title = 'Happy Clients'
		description_html = ''
		show_testimonials = true

	[[params.content_blocks]]
		block = 'blog-section'
		title = 'Recent Posts'
		description_html = '<p>Vonge blog features productivity, tips, inspiration and strategies for massive profits. Find out how to set up a successful blog or how to make yours even better!</p>'
		link_url = '/posts'
		show_posts = true

	[[params.content_blocks]]
		block = 'newsletter'
		newsletter_title = 'Join my mailing list'
		newsletter_description = 'Get inspiration, updates and, cool stuff!'
		newsletter_identifier = ''
		newsletter_button = 'Subscribe'

	[[params.content_blocks]]
		block = 'contact-form'
		form_title = 'Get in touch'
		form_description = 'Vonge comes with a built-in contact form.'
		form_success_page = ''
		form_submission_email = 'site@example.com'
		form_button_text = 'Send now'
